inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'app/assets/builds/**/*'
    - 'coverage/**/*'

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

RSpec/MultipleExpectations:
  Max: 8
  Exclude:
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Max: 25
  Exclude:
    - 'spec/requests/**/*'